server:
  port: 8087
spring:
  application:
    name: customer-service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.40.1:8761/eureka/
feign:
  hystrix:
    enabled: true
provider-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule