server:
  port: 8761

eureka:
  client:
    service-url:
      defalutZone: http://192.168.40.1:8761/eureka/
    #表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据
    fetch-registry: false
    #是否将当前项目放入注册中心 注册中心无需放
    register-with-eureka: false